name: learn-github-actions
on: [push]
jobs:
  check-nacre-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install .
      - run: npm install --global
      - run: nacre --version
