name: run-test
on: [push]
jobs:
  main:
    runs-on: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install .
      - run: npm run test
      - run: npm install --global
      - run: nacre --version
