name: run-test
on: [push]
jobs:
  main:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11, windows-2022]
        node: ['17']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install .
      - run: npm run build
      - run: npm run test:unit
      - run: npm run test:integration
      - run: npm install --global .
      - run: npm run test:system
