name: run-test
on: [push]
jobs:
  main:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node: ['16']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install .
      - run: npm run test
      - run: npm install --global
      - run: nacre --version
